# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

#osx_image: xcode7.3
#language: objective-c
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
#script:
#- set -o pipefail && xcodebuild test -workspace Example/MMSLayeredView.xcworkspace -scheme MMSLayeredView-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
#- pod lib lint

language: objective-c
osx_image: xcode7.3
cache: cocoapods
podfile: Example/Podfile
before_install:
- rvm use system
- sudo gem install bundler
- sudo gem install cocoapods #  Since Travis is not always on latest version
- sudo gem install xcpretty --no-rdoc --no-ri --no-document --quiet
- sudo gem install xcpretty-travis-formatter --no-rdoc --no-ri --no-document --quiet
- pod install --project-directory=Example

script:
- pod lib lint --quick
- set -o pipefail && xcodebuild clean test -workspace Example/MMSLayeredView.xcworkspace -scheme MMSLayeredView-Example -sdk iphonesimulator PLATFORM_NAME=iphonesimulator ONLY_ACTIVE_ARCH=NO -destination 'platform=ios Simulator,name=iphone 6,OS=9.2' | xcpretty;
