# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage
#

language: objective-c
osx_image: xcode8.3

script:
- set -o pipefail && xcodebuild test -workspace Example/MMSLayeredView.xcworkspace -scheme MMSLayeredView-Example -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.3' | xcpretty
- pod lib lint
